name: Build and Deploy Advent Calendar

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout das Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Richtiges Java-SDK einrichten
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Maven-Abhängigkeiten herunterladen und Projekt bauen
      - name: Build with Maven
        run: |
          mvn clean package

      # 4. Artefakte speichern (Optional: JAR oder jlink-Bild hochladen)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: advent-calendar-artifacts
          path: target/*.jar

  deploy:
    needs: build  # Dieser Job läuft nur nach erfolgreichem Build
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout das Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Java (falls nötig)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Deploy zu GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
